### ISSUE TITLE
Camera Feature

### ISSUE THREAD

**Issue by gysiang** [gysiang/miniRT#10]
1. Learn how the camera works for ray tracing and how to use the data given to implement something in the code
2. Learn how ray tracing works and find the relevant formulas that might be needed.

**Comment by itben-h** [comment]
Here are some resources on raytracing that i've used:
https://www.scratchapixel.com/index.html
https://www.purplealienplanet.com/node/20
https://raytracing.github.io/books/RayTracingInOneWeekend.html

**Comment by gysiang** [comment]
1. Need to handle keyboard movement of WASD to move the camera.
2. Image needs to be re-rendered after the camera is moved.

**Comment by itben-h** [comment]
> 1. Need to handle keyboard movement of WASD to move the camera.
> 
>     2. Image needs to be re-rendered after the camera is moved.

Don't actually need to do this, not part of mandatory.  Not even part of bonus either. Would be nice feature to have though.
